version: '3.8'

services:
  db-dev:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: user_dev_password
      POSTGRES_DB: quejas_db_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: