name: Create branch from issue

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE=${{ github.event.issue.title }}
          # Sanitizar el título (quitar espacios y mayúsculas)
          BRANCH_NAME="issue-${ISSUE_NUMBER}-$(echo "$ISSUE_TITLE" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-')"
          
          echo "Creando rama: $BRANCH_NAME"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin
          git checkout -b $BRANCH_NAME origin/main
          git push origin $BRANCH_NAME
